### ISSUE TITLE
Práctica 3 Plano Cartesiano

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/practica-6-relaciones-funciones-y-plano-cartesiano-equipo-edwin#1]
[Practica 3 Plano Cartesiano.pdf](https://github.com/user-attachments/files/17168603/Practica.3.Plano.Cartesiano.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by BautistaLizbeth** [comment]
Portada. 5/5
Procedimiento. 5/5
Figuras, ilustraciones y fotografías. 5/5
Resultados y conclusiones. /5
Calificación: 20/20

Calificado por: María Lizbeth Bautista García.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
